'use strict';

module.exports = {
    INITIALIZE: 'INITIALIZE',
    CREATE_AUTHOR: 'CREATE_AUTHOR',
    DELETE_AUTHOR: 'DELETE_AUTHOR',
    UPDATE_AUTHOR: 'UPDATE_AUTHOR',

    GET_USAGE: 'GET_USAGE'
};
